## ReadTheDocs Configuration File ##

# syntax version
version: 2

# Build Engine used by ReadTheDocs
sphinx:
  builder: html
  configuration: docs/docu/conf.py

# Additional formats for ReadTheDocs to output
formats:
  - pdf

python:
  version: 3.7
  install:
    - requirements: docs/docu/rtds_requirements.txt
