## ReadTheDocs Configuration File ##

# syntax version
version: 2

# Build Engine used by ReadTheDocs
sphinx:
  builder: html
  configuration: docs/conf.py

# Additional formats for ReadTheDocs to output
formats: []

python:
  version: 3.7
  install:
    - requirements: docs/requirements.txt
